apiVersion: v1
kind: Service
metadata:
  name: app-ninja-service
  namespace: ninja
spec:
  type: LoadBalancer
  selector:
    app: app-ninja
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080